### ISSUE TITLE
Subscriber widget argument should be `builder` not `child`

### ISSUE THREAD

**Issue by lalomartins** [buijs-dev/klutter#20]
Subscriber widgets take a `Widget child(value)` argument. In the Flutter API, all such arguments are called `builder`, so calling it `builder` would make things easier to understand (`child` arguments are actual Widget objects, not functions). Also, it should pass the BuildContext as a `context` argument: `Widget builder(context, value)`.

**Comment by buijs-dev** [comment]
Thanks for the feedback. 👍

**Comment by buijs-dev** [comment]
Think I'll add this to 2023.2.1.beta

**Comment by buijs-dev** [comment]
Change added to klutter_ui [1.0.0](https://pub.dev/packages/klutter_ui). 
Will bump klutter_ui version in klutter dart/gradle libs.
