### ISSUE TITLE
App does not run on iOS simulator (M1 Mac)

### ISSUE THREAD

**Issue by DK070202** [buijs-dev/klutter#4]
It's an amazing project, and i would like to try this but problem is, just gone trough the document, and i can not find a plugin type example. I have been trying to set it up but it did not work. If there is pre build plugin from which i can take reference it would be great help.

**Comment by buijs-dev** [comment]
I made a small tutorial to create a plugin project on my website. Maybe that can help you get started: https://buijs.dev/klutter-2/. 

The starting point for a plugin is a standard Flutter plugin. So create a new Flutter project and then follow the steps described here: https://github.com/buijs-dev/klutter-dart

I'm working on an IDE plugin for Intellij and Android Studio with which you can create a Klutter project with the standard wizard. That'll make it a lot easier. Will be available in a few weeks probably. 

Thanks for your interest and let me know if this is enough to get you started!

**Comment by DK070202** [comment]
Thanks. It will be game changing for community, it will totally change how we are building plugins today. I just love this project.

**Comment by DK070202** [comment]
I have gone through document and still I am facing issue while running on simulators.

When i try to run `flutter pub run klutter:consumer init` it throw the error  Path does not exist: /root/android/app. And when i try to run this it show that missing /root/ios/podfile.

**Comment by buijs-dev** [comment]
What exception do you get with Java 18? To be safe just stick to Java 8 or 11, there's no benefit in newer versions because you're using Kotlin anyway. 

Which klutter version are you using? 0.1.3?
Producer tasks should be run in the root folder of a flutter plugin project
Consumer tasks should be run in the example folder for testing (root/example).

Did you run both platform tasks in the root folder? That is:
- flutter pub run klutter:producer install=platform
- flutter pub run klutter:producer install=library

Then in the root/example folder you run the consumer tasks:
- flutter pub run klutter:consumer init
- flutter pub run klutter:consumer add=<name of your plugin>

**Comment by DK070202** [comment]
Yeah, I have tried but i forget to add klutter plugin to example, so that's why it was throwing error. Now it's working perfectly for android but in iOS still throws error.
## Repo. link
https://github.com/DK070202/plugin

## Error
Failed to build iOS app
Error output from Xcode build:
↳
    2022-08-07 13:05:16.287 xcodebuild[3676:37731] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-08-07 13:05:16.287 xcodebuild[3676:37731] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/n6/j3j1ynh53k5dlpgxk9d_drrw0000gn/T/flutter_tools.oIhM9m/flutter_ios_build_temp_dirWa3wuw/temporary_xcresult_bundle
    ld: framework not found plugin
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	/var/folders/n6/j3j1ynh53k5dlpgxk9d_drrw0000gn/T/flutter_tools.oIhM9m/flutter_ios_build_temp_dirWa3wuw/temporary_xcresult_bundle

**Comment by buijs-dev** [comment]
I checked out your repository and both iOS an Android work on my machine... 

The log is not very helpful unfortunately because the actual problem is not displayed. I am not sure I can help you with this. Make sure you have the latest xcode version installed and possibly try to install the xcode command line tools separately. 

Have you tried creating a new flutter plugin project (without klutter) and run that on an iOS simulator?

Just to be sure... you running this locally on a mac device? Any other device offcourse won't work for iOS.

**Comment by DK070202** [comment]
Yeah I have pre installed Xcode cmd tools. And yeah i can create and run other project on iOS simulator.

**Comment by buijs-dev** [comment]
Try this:

1. Create a new flutter plugin project
2. Run the example app on Android
3. Run the example app on iOS
4. Add klutter dependency
5. Run init/install in root
6. Run init/add in example
7. Rerun example app on Android
8. Rerun example app on iOS

Just to be sure. Let me know if that helps.

**Comment by DK070202** [comment]
Gone through all the steps.
Before klutter consumer command

<img src="https://user-images.githubusercontent.com/78605453/183293656-a88d6e89-5663-4860-9a6d-285f48243468.png" width="400"  />


After 

<img src="https://user-images.githubusercontent.com/78605453/183293987-4772d205-71b3-4c9c-9f15-59773cdf48af.png" width="100%" />

**Comment by buijs-dev** [comment]
Ah thank you for the screenshot. I can see the issue now. The platform module is not build for iOS Simulator architecture so you are unable to start the app. What device do you use? Intel mac or a M1/M2?

**Comment by DK070202** [comment]
Apple Mac M1 2021

**Comment by buijs-dev** [comment]
Okay thank you, then that's the problem. We need to exclude different architecture for the M1. I will look into it and get back to you.

**Comment by DK070202** [comment]
Thanks. @buijs-dev.Is there any doc for passing args from flutter/dart side ?

**Comment by DK070202** [comment]
Is there any guide line around passing arguments through `invokeMethod`  ?.

**Comment by buijs-dev** [comment]
Passing arguments is not yet supported in the klutter 0.1.3. I have implemented it on develop though so it won't be to long before it's released.

**Comment by buijs-dev** [comment]
@DK070202 Can you check the PR I opened and see if you can now run your project on a Simulator? I added the iosSimulatorArm64 to the platform gradle file. Run 'flutter pub run klutter:producer install=platform' again. I don't have a M1 (yet) so can not test it myself.

**Comment by DK070202** [comment]
Hey, @DK070202 I have `flutter pub run klutter:producer install=platform` run this after merging ur PR to master but it didn't work. Here is snap.

<img width="1283" alt="Screenshot 2022-08-11 at 11 05 17 PM" src="https://user-images.githubusercontent.com/78605453/184197324-f1c37ed2-9b8f-45e0-b2c0-c16b37907efe.png">

**Comment by buijs-dev** [comment]
I just did flutter pub get and then flutter pun run klutter:producer install=platform on your main branch and it works. 

Did you do a flutter pub get before running the install=platform command?

Flutter doctor output?

**Comment by DK070202** [comment]
Yeah, i did same.
Here is output of `flutter doctor -v`

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2 21D49 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/dhruvin/Developement/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dhruvin/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.70.0)
    • VS Code at /Users/dhruvin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 8993E0B8-CCFB-4CD7-946C-5096D3358FBF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by buijs-dev** [comment]
Hm. Can you delete your local workspace and do a fresh checkout of the repo from git? I think your iOS/xcode project might have issues. Kinda hard to debug from here but if you do a fresh checkout you'll have the same starting point as me.

So delete your local copy.
Checkout main.
Run flutter pub get in root.
Run install platform in root.

Let me know if this helps.

**Comment by DK070202** [comment]
I have deleted local project and tried again but same result as previous run.

**Comment by buijs-dev** [comment]
Open the runner.xcworkspace in xcode and rerun flutter pub get, klutter producer install.

**Comment by DK070202** [comment]
I have tried this when I get module not found, and i have tried again but didn't work.

**Comment by buijs-dev** [comment]
Okay last thing I can think of for now...

1. In root run flutter clean
2. In root run flutter pub get
3. In root/ios remove Pods Podfile.lock
4. In root/ios run pod install
5. Open Runner.xcworkspace in xcode and check for any warnings/fix the warnings
6. Build app in xcode
7. Run app on simulator

**Comment by DK070202** [comment]
> Okay last thing I can think of for now...
> 
> 1. In root run flutter clean
> 2. In root run flutter pub get
> 3. In root/ios remove Pods Podfile.lock
> 4. In root/ios run pod install
> 5. Open Runner.xcworkspace in xcode and check for any warnings/fix the warnings
> 6. Build app in xcode
> 7. Run app on simulator
There is no podfile or podfile.lock at `root/ios`.

**Comment by buijs-dev** [comment]
Yes in example folder!

**Comment by DK070202** [comment]
Thanks for quick support, but I didn't work. Fill free to connect to reproduce or if you want more logs or information.

**Comment by buijs-dev** [comment]
No problem. I just ordered a M1 pro so I can test this myself. Will get back to you.

**Comment by DK070202** [comment]
Thanks, @buijs-dev.

**Comment by buijs-dev** [comment]
Managed to reproduce and fix this on a M1 macbook. Will ship a fix with the next release which will use XCFramework instead of a fat framework.

**Comment by DK070202** [comment]
Thanks, @buijs-dev waiting for the next release.

**Comment by buijs-dev** [comment]
@DK070202 Next release is available [0.2.1](https://pub.dev/packages/klutter). Best is to create a new flutter plugin project and then add the 0.2.1 version. It will apply the new klutter gradle plugin. Feel free to contact me if you have any other issues or ideas!
