### ISSUE TITLE
Streams api support

### ISSUE THREAD

**Issue by JenshenSoft** [buijs-dev/klutter#5]
Wow, what a great project :) 

You've done really impressive work. 

What do you think about supporting streams API? It's commonly used in flutter plugins.

Kotlin multiplatform side: 
`
  fun observeLocation() : Flow<Location> 
`

Dart side: 

`
  Stream<Location> observeLocation();
`
https://api.flutter.dev/flutter/services/EventChannel-class.html

I've done it for my own plugin. Would be great to have such a feature supported by Klutter. 
Thanks in advance.

**Comment by buijs-dev** [comment]
Thank you for the kind words! 

I have looked into using event channels and it is definitely possible to add support for it. Can't say if/when it could be added though.

Could you provide a link to your plugin? I am interested to see your solution.

**Comment by buijs-dev** [comment]
Eventchannel support is available from klutter 2023.1.1.beta (dart 0.3.0).

**Comment by erksch** [comment]
Can you provide an example on how to use the `EventChannel` support Klutter?

**Comment by buijs-dev** [comment]
> Can you provide an example on how to use the `EventChannel` support Klutter?

See the stateless-ui recipe in the [cookbook](https://github.com/buijs-dev/klutter-cookbook).

**Comment by erksch** [comment]
I see. Your `@Controller` annotated Kotlin class has to subclass `Publisher`.
This creates an `EventChannel` with the name of the controller.
The corresponding generated Dart class subclasses [`Subscriber`](https://github.com/buijs-dev/klutter-dart-ui/blob/main/lib/src/subscriber.dart).

The recipe you mentioned [has no generated android](https://github.com/buijs-dev/klutter-cookbook/tree/main/stateless_ui/android) or iOS plugin classes. Is this correct? 
The `EventChannel` would need to be wired in the plugin native files.

**Comment by buijs-dev** [comment]
The compiler plugin will generate all the boilerplate code for Android and iOS. Just run kradle build (or gradlew install -p platform) first to see it.
